### ISSUE TITLE
add filter on which weaviate to send query to

### ISSUE THREAD

**Issue by laura-ham** [SeMI-network/weaviate-graphql-prototype#28]
For the Network queries, it should be possible to specify the Weaviate network(s) to send the query to. This could look like:

``` graphql
{
    Network(network: "n_3") { ... }
}
```

**Comment by bobvanluijt** [comment]
@laura-ham Not sure I follow concerning Local. Local is only one instance, right?

**Comment by laura-ham** [comment]
@bobvanluijt In Rafael's UI design, there is an option to choose which local Weaviate to query, and which network to query. That's why I thought this should also be specified in the query you make

**Comment by bobvanluijt** [comment]
Not sure which design you are referring too, can you please share (via email or Slack)?

**Comment by laura-ham** [comment]
@bobvanluijt Could you verify the updated issue? 
Questions:
- Is it a specific 'network' that you target? Or more like a group of p2p nodes one should specify?
- Is it possible to target multiple networks at the same time? (Then I will update the design according to this before implementing)

**Comment by bobvanluijt** [comment]
IS this still relevant @laura-ham ? IF not please close :-)

**Comment by laura-ham** [comment]
> Is this still relevant @laura-ham ? IF not please close :-)

That's more a question from me to you at this moment ;) see my previous comment

**Comment by bobvanluijt** [comment]
Sorry, missed those question.

Answer is simple: **No** :-)

You can only target the network you are in, you can only be in one network.

So I can close this one ;-)
